import AddNotes from "@/components/addNotes";
import Head from "next/head";
import styles from '../styles/Home.module.css'
import ShowNotes from "@/components/showNotes";
export default function Home() {
  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper}>
        <div className={styles.container}>
          {/* <Notes /> */}
        <AddNotes />
        <ShowNotes />
        </div>
      </main>
    </>
  );
}
